stages:
  - build
  - push
  - deploy

variables:
  AWS_REGION: "eu-west-2"
  IMAGE_NAME: "test-app"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  VERSION_TAG: "wowcher-v1.0.0"
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  IMAGE_URI: "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"

# -----------------------------------
# 🔹 LOGIN TO AWS & ECR
# -----------------------------------
.before_aws_login: &aws_login
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

# -----------------------------------
# 🔹 BUILD DOCKER IMAGE
# -----------------------------------
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

# -----------------------------------
# 🔹 PUSH TO ECR
# -----------------------------------
push:
  stage: push
  image: docker:24.0.5
  services:
    - docker:dind
  <<: *aws_login
  script:
    # Docker Build
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    # Tag image for ECR
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_URI

    # Push commit-based image
    - docker push $IMAGE_URI

    # Tag and push version tag
    - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$VERSION_TAG
    - docker push $ECR_REGISTRY/$IMAGE_NAME:$VERSION_TAG
